### ISSUE TITLE
hotrod.yaml is not a yaml file

### ISSUE THREAD

**Issue by marcindulak** [udacity/CNAND_nd064_C4_Observability_Starter_Files#18]
@SudKul - the yaml is actually a cat to kubectl pipe. This file has been introduced in https://github.com/udacity/CNAND_nd064_C4_Observability_Starter_Files/blob/850f0c23867ce391c32b101aa00dd35ef0065abf/Exercise_Starter_Files/hotrod.yaml

**Comment by SudKul** [comment]
Yes, @marcindulak 
I have marked it as YAML intentionally so that a learner can copy the entire file content and run it in the Vagrant VM terminal. 
Otherwise, a leaner will have to copy (or create) the `hotrod.yaml` file in the VM before running the `kubectl apply` command. 

Let me know  if you have other suggestions. If you are stuck on any step, consider wiping out the VM and start over. Feel free to reach out to the mentors on https://knowledge.udacity.com/

Happy learning.

**Comment by marcindulak** [comment]
If this was yaml, one would just `kubectl create -f hotrod.yaml`. This is what most k8s users would expect.

**Comment by marcindulak** [comment]
Maybe calling this file `hotrod.sh` is also a solution.
